config/routes.rb
Gollazos::Application.routes.draw do

  

  get "activities/index"
  get "friendship/index"
  get "redireccion/index"
  get "redireccion/new"
  get "metrics/index"
  get "metrics/emails"

  resources :invitations do
    post 'postear', :on => :collection
  end
  resources :invitacion2

  resources :partidos do
      post 'repartir', :on => :collection
      resources :bets
  end

  resources :users do
    resources :profiles
  end
  resources :redireccion
  resources :friendships
  resources :activities

  get "home/index"
  get "home/index2"
  get "home/reglamento"
  get "home/contacto"
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  match "home/:invitation_token" ,to: "home#referido"
  match "/:invitation_token" ,to: "home#index"

   root :to => 'home#index'
   

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :bets, :dependent => :destroy
  has_many :partidos, :through => :bets, :uniq => true

  has_one :profile

  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key =>"friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user


  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  # Setup accessible (or protected) attributes for your model
  #attr_accessible :email, :password, :password_confirmation, :remember_me
  #attr_accessible :name, :oauth_expires_at, :oauth_token, :provider, :uid
  attr_accessible :name, :oauth_expires_at, :oauth_token, :provider, 
                  :uid, :pezzos, :administrator, :invitation_token, :visits_number, 
                  :invitation_number, :invitation_id, :post_on_fb, :bets_number, :age,
                   :pezzos_que_apuesta, :local_apostado, :visitante_apostado, :referidos


  validates :pezzos, :numericality => {:greater_than_or_equal_to => 0, :message => "no puedes tener menos de 0 pezzos"}
  #INVITATION before_create :set_invitation_limit
  #----este si se necesita validates_presence_of :invitation_id, :message => 'is required'
  #validates_uniqueness_of :invitation_id

  has_many :sent_invitations, :class_name => 'Invitation', :foreign_key => 'sender_id'
  #belongs_to :invitation


def self.from_omniauth(auth)
  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.profile = Profile.new
    #email
    if auth.info.email == nil
      
    else
      user.email = auth.info.email
    end
    
    #------
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.save!    
  end
end


#invitaciones

def facebook
  @facebook ||= Koala::Facebook::API.new(oauth_token)
end

def friends_count
  facebook.get_connection("me","friends").size
end

  def descontar_pezzos(monto)
    pezzos_total = self.pezzos - monto
    self.update_attributes(pezzos: pezzos_total)
  end
  def consignar_pezzos(monto)
    pezzos_total = self.pezzos + monto
    self.update_attributes(pezzos: pezzos_total)
  end
  def aumentar_visitas
    visitas_total = self.visits_number + 1
    self.update_attributes(visits_number: visitas_total)
  end
  def aumentar_invitaciones
    invitaciones_total = self.invitation_number + 1
    self.update_attributes(invitation_number: invitaciones_total)
  end
  def aumentar_referidos
    referidos_total = self.referidos + 1
    self.update_attributes(referidos: referidos_total)
  end
  def aumentar_apuestas
    apuestas_total = self.bets_number + 1
    self.update_attributes(bets_number: apuestas_total)
  end
  def aumentar_posts
    posts_total = self.post_on_fb + 1
    self.update_attributes(post_on_fb: posts_total)
  end
  
  def position(column = 'pezzos', order = 'DESC')
    order_by = "#{column} #{order}"
    arrow = order.capitalize == "ASC" ? "<=" : ">="
    User.where("#{column} #{arrow} ?", self.send(column)).order(order_by).count
  end  
  def followers
    followers = []
    self.inverse_friends.each do |follower|
      followers.push(follower)
    end
    return followers
    #return self.inverse_friendships
  end

  def followers_ids
    followers = []
    self.followers.each do |follower|
      followers.push(follower.id)
    end
    return followers
  end


  def following
    following = []
    self.friendships.each do |follower|
      following.push(follower.friend)
    end
    return following
    #return self.friendships
  end

  def following_ids
    following = []
    self.following.each do |follower|
      following.push(follower.id)
    end
    return following
  end

  def correos_usuarios
    usuarios = User.where("email is NOT NULL", nil)
    return usuarios
  end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ActionController::Base
  protect_from_forgery
  def facebook

     # with this code you can see the data sent by facebook
     omniauth = request.env["omniauth.auth"] 

    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      #@user.consignar_pezzos(50000)
      session[:user_id]= @user.id
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login

  def index
    @users= User.paginate(page: params[:page], per_page: 15).order("pezzos DESC")
    if params[:page]==nil
      @page = 1
    else
      @page = ((params[:page].to_i - 1) * 15) + 1  
    end

  end

  def show
    @user_ranking = User.order("pezzos DESC").limit(10)
    @user= User.find(params[:id])
    if @user.profile ==nil
      @user.profile =Profile.new
    end

    if @user.partidos.any?
      if params[:partidoId]
        @partido= Partido.find(params[:partidoId])
      else
        @partido = @user.partidos.first
      end

      @bets= @partido.bets.where("user_id = ?", @user.id) 
    end   
    #@pezzos_por_amigos= User.where('invitation_id = ?', @user.id).count * 50000
    @pezzos_por_amigos= @user.referidos * 5000
    @pezzos_por_actividad= @user.bets.count * 5000

  end

  def update
  	current_user.update_attributes(params[:user])
    @partido = Partido.find(params[:partido_actual_id])
    respond_to do |format|
      format.html { redirect_to :back}
      format.js
    end
  end

end

app/views/users/_user_apostaria.html.erb
<div class="alert alert">
    <strong>Te gustaría poder apostar dinero real por tus equipos favoritos?</strong> <br/> 
    <div class="formulario-sameline">
      <%= form_for [current_user, current_user.profile], :html => { :class => 'form-horizontal' } do |f| %>
        <%= f.hidden_field :apostaria, value: true %>
        <button   class="btn btn-primary" data-dismiss="ale2rt">
        Si, deseo apostar dinero real!
        <% f.submit ""%> 
        </button> 
      <%end%>
    </div>

    <div class="formulario-sameline">
      <%= form_for [current_user, current_user.profile], :html => { :class => 'form-horizontal' } do |f| %>
        <%= f.hidden_field :apostaria, value: false %>
        <button   class="btn" data-dismiss="ale2rt">
        No
        <% f.submit ""%> 
        </button> 
      <%end%>
    </div>
</div>
 

app/views/users/_user_mi_perfil.html.erb
<div class="span9 BTSinEspacio">
<p class= "lead">¡Hola <font face="FUTURAB" color="#005798"><%=@user.name%></font>! </p>
<p><font face="FUTURAB" color="#005798">TIENES</font><font size="18" face="digital7" color="orange"><%=number_to_currency(current_user.pezzos,:precision => 0)%></font> <font face="FUTURAB" color="#005798">PEZZOS</font>     / ACTUALMENTE ESTAS EN LA POSICIÓN <strong><font size="18" color="#005798"><%=@user.position%></font></strong> DEL RANKING</p>
<%= link_to  new_invitation_path do%>
	<%= image_tag "user/btnGanarPezzos_menu.png"%>
<%end%>
<%= render "user_profile"%>
</div>
<font face="Futura Book BT">

app/views/users/_user_profile.html.erb
<a href="" data-toggle="modal" data-target="#myProfile">
  Actualizar mi Perfil
</a>
<div id="myProfile" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<%= form_for [@user, @user.profile], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">¡Actualizar Mi Perfil!</h3>
  </div>

  <div class="modal-body">

  <div class="control-group">
    <%= f.label :pais, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :pais, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :ciudad, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ciudad, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :direccion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :direccion, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :celular, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :celular, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :twitter, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :twitter, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :equipos_favoritos, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :equipos_favoritos, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :camiseta_de, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :camiseta_de, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :talla, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :talla, :class => 'text_field' %>
    </div>
  </div>
  </div>
  <div class="modal-footer">
  
	<%= f.hidden_field :nombre, value: @user.name%>
    <button class="btn">
    	Actualizar Perfil
		<% f.submit ""%> 
    </button>	
       
  </div>
  <%end%>
</div>

app/views/users/_user_profile_boton.html.erb
<button href="" data-toggle="modal" data-target="#myProfile" class="btn btn-primary">
  Actualizar mi Perfil
</button>
<div id="myProfile" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<%= form_for [@user, @user.profile], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">¡Actualizar Mi Perfil!</h3>
  </div>

  <div class="modal-body">

  <div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Obtén $50,000 pezzos llenando tu perfil!</strong> <br/> Actualiza la información de tu perfil para ganar mas pezzos.
  </div>
  <div class="control-group">
    <%= f.label :pais, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :pais, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :ciudad, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ciudad, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :direccion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :direccion, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :celular, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :celular, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :twitter, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :twitter, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :equipos_favoritos, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :equipos_favoritos, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :camiseta_de, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :camiseta_de, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :talla, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :talla, :class => 'text_field' %>
    </div>
  </div>
  </div>
  <div class="modal-footer">
  
	<%= f.hidden_field :nombre, value: @user.name%>
    <button class="btn">
    	Actualizar Perfil
		<% f.submit ""%> 
    </button>	
       
  </div>
  <%end%>
</div>

app/views/users/_user_tu_perfil.html.erb
<div class="span9 BTSinEspacio">
<p class= "lead"><font face="FUTURAB" color="#005798"><%=@user.name%></font>!</p>
<p><font face="FUTURAB" color="#005798">TIENE </font><font size="18" face="digital7" color="ffd200"><%=@user.pezzos%></font> <font face="FUTURAB" color="#005798">PEZZOS</font>     / ACTUALMENTE ESTÁ EN LA POSICIÓN <strong><font size="18" color="#005798"><%=@user.position%></font></strong> DEL RANKING</p>
<%= link_to  new_invitation_path do%>
	<%= image_tag "user/btnGanarPezzos_menu.png"%>
<%end%>
</div>
<font face="Futura Book BT">

app/views/users/index.html.erb
<div class= "header-title">
  <div class="container">
    <div class="row">
      <div class="span6 fuenteFuturaB titulo-blanco">
        <p> <p>
        <h3><%=image_tag "ranking/btn_rankingTitulos.png"%>JUGADORES</h3>
      </div>
    </div>
  </div>
</div>
<%=render "partidos/redes_sociales"%>
<div class="container">
  <div class="row centro">
    <%= will_paginate %>
    <div class="span6 offset3 BTSinEspacio partidos-ranking">
      
  <table class="table">
    <thead>
      <tr>
        <th>Posición</th><th>Nombre</th><th>Pezzos</th><th># Apuestas</th>
      </tr>
    </thead>
    <tbody>
      <%count = @page %>
      <%@users.each do |user|%>
        <tr>
          <td>
            <%=count%>
          </td>
          <td>
            <div class="jugador">
              <%=image_tag current_user.facebook.get_picture(user.uid, {type: "square"}), {:class=> "", :width=>"30"}%>  <%=link_to user.name, user%></span></td><td><%= number_to_currency(user.pezzos,:precision => 0)%></td><td><%= user.bets.count%></td>
            </div>
        </tr>
        <%count +=1%>
      <%end%>
    </tbody>
  </table>
  
</div>
<%= will_paginate %>
  </div>
</div>

app/views/users/show.html.erb
<div class= "">
	<%= render "layouts/flash_notice"%>
  <div class="container">
    <div class="row user-photo">
    	<div class="span2">
    		<%=image_tag current_user.facebook.get_picture(@user.uid, {type: "large"}), {:class=> "thumbnail"}%>
    	</div>
    	<% if current_user.id == @user.id%>
    		<%=render "user_mi_perfil"%>
    	<%else%>
    		<%=render "user_tu_perfil"%>
    	<%end%>
    </div>
  </div>
</div>

<div class="user-separador"></div>
<div class= "">
  <div class="container">

    <div class="row">
      <div class="span12 offset">
	  	<div class="row">
	  		<div class="span3">
	  			<%= image_tag "user/btnTuspartidosJugados_perfil.jpg"%>
	  			<ul class="nav nav-tabs nav-stacked">
		  			<% @user.partidos.each do |partido|%>
		  				<li class=<%="active" if @partido.id == partido.id%>>
		  					<%= link_to user_path(@user, partidoId: partido.id ) do%>

						      <h6> <%= l(partido.diapartido, format: '%d de %B %l:%M %p', locale:'es-CO')%></h6>
						      <div class="centro">
							      <%= image_tag partido.logolocal, {:class => "", :width=>"50px"}%>
							      <%partido.local%>
							      <strong>Vs</strong>
							      <% partido.visitante%>
							      <%= image_tag partido.logovisitante,{:class => "", :width =>"50px"}%>
						      </div>
		  					<%end%>
		  				</li>
		  			<%end%>  
				</ul>
	  		</div>

	  		<div class="user-separador-abajo span6">
	  			<div class="row">
	  				<div class= "span6">
	  					<%if @user.partidos.any?%>
	  					<div class="row">
						    <div class="partido-fecha span5 ">
						      <h4> <%= l(@partido.diapartido, format: '%d de %B', locale:'es-CO')%></h4>
						      <h6 class="muted"> <%= l(@partido.diapartido, format: '%l:%M %p', locale:'es-CO')%></h6>
						    </div>
						    <div class="">
							    <div class=" span2 logo">
							      <%= image_tag @partido.logolocal, {:class => "", :width=>"100px"}%>
							      <div>
							          <h2 class="lead"> <%=@partido.local%></h2>      
							          <h6 class="muted">Local</h6>
							      </div>
							    </div>
							    <div class="span1">
							    	<%=image_tag "partido/VS_partidos.png",{:class => "user-vs"}%>
							    </div>
							    <div class="span2 logo">
							      <%= image_tag @partido.logovisitante,{:class => "", :width =>"100px"}%>
							      <div>
							        <h2 class="lead"> <%=@partido.visitante%></h2>
							        <h6 class="muted"> Visitante</h6>
							      </div>
							    </div>
						    </div>
						  </div>
						  <hr>
						  
	  					  <table class="partidos-ranking-dos">
						    <thead>
						      <tr>
						        <th>Resultado Jugado</th>
						        <th>Pezzos Jugados</th>
						        <th>Retorno <font color="#fff601">Esperado</font></th>
						        <th>Pezzos <font color="#67ff01">Ganados</font></th>
						        <th>Pezzos <font color="#829198">Perdidos</font></th>
						      </tr>
						    </thead>
						    <tbody>
						      <%@bets.each do |bet|%>
						        <tr>
						         <td><%= "#{bet.golesLocal} - #{bet.golesVisitante}"%></td>
						         <td><%= number_to_currency(bet.monto,:precision => 0)%></td>
						         <td><font color="#fff601"><%= @partido.xveces_el_resultado(bet.golesLocal, bet.golesVisitante)%></font></td>
						         <td>
						         	<font color="#67ff01">
								         <% if bet.pezzos_ganados==nil  %>
								         	0
								         <%else%>
								         <%= number_to_currency(bet.pezzos_ganados,precision: 0)%>
								         <%end%>
						     		</font>
						     	</td>
						     	<td>
						     		<font color="#829198">
						     			<%if bet.partido.repartido == true && bet.pezzos_ganados==nil %>
						     				<%= number_to_currency(bet.monto,:precision => 0)%>
						     			<%else%>
						     				0
						     			<%end%>
						     		</font>
						     	</td>
						        </tr>
						      <%end%>
						    </tbody>
						  </table>
						   
						<%else%>
			  				<%if current_user.id == @user.id%>
			  					<div class="">
				  					<h6>NO HAS JUGADO POR NINGÚN PARTIDO!</h6>
				  					    <%= link_to  partidos_path do %>
					                    	<%=image_tag "partidos/btnJUEGA_partidos.png"%>
					                    <%end%>
			  					</div>
			  				<%else%>
			  					<div class="">
				  					<h6>NO HA JUGADO POR NINGUN PARTIDO!</h6>
			  					</div>
			  				<%end%>
		  				<%end%>
	  				</div>
	  			</div>
	  		</div>
	  		<div class="span3">
	  			<%=render "partidos/premios_y_ranking"%>
	  		</div>

	  	</div>
	  </div>
    </div>
  </div>
</div>
<div class="user-separador"></div>
<div class= "user-fondoGris">
  <div class="container">
    <div class="row">
      <div class="span12 offset">
	  	<div class="row">
	  		<div class="span3">
	  			<%= image_tag "user/btnTuspezzos_perfil.jpg"%>
	  		</div>
	  		<div class="span5">
	  			<div class= "user-separador-abajo">
	  			<p>Estos son los Pezzos que has adquirido Jugando, Invitando y Compartiendo.</p></div>

	  			<div class="user-gano-pezzos">
	  				<%=image_tag "user/iconoBalon_tusPezzosPerfil.png", {:class =>"", :height =>"30"}%> JUEGOS GANADOS
	  				<span class="user-pezzos pull-right"> <font size="6" face="digital7" color="ffd200"> 
	  					<%=number_to_currency( current_user.bets.sum(:pezzos_ganados),:precision => 0)%> </font>PEZZOS</span>
	  			</div>
	  			<div class="user-gano-pezzos">
	  				<%=image_tag "user/iconoInvitaAmigos_tusPezzosPerfil.png", {:class =>"", :height =>"30"}%>INVITANDO AMIGOS
	  				<span class="user-pezzos pull-right"> <font size="6" face="digital7" color="ffd200">
	  					<%=number_to_currency( @pezzos_por_amigos,:precision => 0)%> </font>PEZZOS</span>
	  			</div>
	  			<div class="user-gano-pezzos">
	  				<%=image_tag "user/iconoActividad_tusPezzosPerfil.png", {:class =>"", :height =>"150"}%> ACTIVIDAD
	  				<span class="user-pezzos pull-right">
	  				<font size="6" face="digital7" color="ffd200"> <%=number_to_currency(  @pezzos_por_actividad,:precision => 0)%></font> PEZZOS</span>
	  			</div>

	  		</div>
	  	</div>
	  </div>
    </div>
  </div>
</div>

<div class="user-separador">
  <div class="centro">
    <div class="span6 offset3 caja-blanca invita-amigos-footer">
    	<div class="areaPremios"></div>
    	
      <font face="Futura Book BT">¡INVITA A TUS AMIGOS Y COMPARTE JUEGOS PARA GANAR MÁS PEZZOS!
    </font>
    
    </div>
    <div class="areaPremios"></div>

    <div class="areaPremios">
    <%= link_to  new_invitation_path do%>
	<%=image_tag "user/logo_facebook.png", {:class => "", :width=>"50"}%> 
	<%end%>
  
  	</div>
  </div>
</div>

app/views/users/update.js.erb
$("#botonesmontos").html("<%= escape_javascript(render('partidos/apuesta_diez')) %>");
$("#matriz").html("<%= escape_javascript(render('partidos/botones_apuestas')) %>");
$("#formulario").html("<%= escape_javascript(render('partidos/formulario_apuesta')) %>");