config/routes.rb
Gollazos::Application.routes.draw do

  

  get "activities/index"
  get "friendship/index"
  get "redireccion/index"
  get "redireccion/new"
  get "metrics/index"
  get "metrics/emails"

  resources :invitations do
    post 'postear', :on => :collection
  end
  resources :invitacion2

  resources :partidos do
      post 'repartir', :on => :collection
      resources :bets
  end

  resources :users do
    resources :profiles
  end
  resources :redireccion
  resources :friendships
  resources :activities

  get "home/index"
  get "home/index2"
  get "home/reglamento"
  get "home/contacto"
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  match "home/:invitation_token" ,to: "home#referido"
  match "/:invitation_token" ,to: "home#index"

   root :to => 'home#index'
   

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  attr_accessible :sender_id, :recipient_uid, :token, :sent_at, :used, :demora, :created_at

	belongs_to :sender, :class_name => 'User'
	has_one :recipient, :class_name => 'User'

	validates_presence_of :recipient_uid
	validate :recipient_is_not_registered
	#validate :sender_has_invitations, :if => :sender

	#before_create :generate_token
	#before_create :decrement_sender_count, :if => :sender
	#ADDED: incrementa las invitaciones
	#before_create :increment_sender_count, :if => :sender

	def actualizar_used
    	usedT = true
    	#self.used = true
    	self.update_attributes(used: usedT)
  	end
  	def actualizar_demora
    	demoraT = (Time.now - self.created_at.to_time)/1.day
    	#self.demora = demoraT
    	self.update_attribute(:demora, demoraT)
    	#self.update_attributes(demora: demoraT)
  	end
	private
 
	def recipient_is_not_registered
	  errors.add :recipient_uid, 'is already registered' if User.find_by_uid(recipient_uid)
	end

	# def sender_has_invitations
	#   unless sender.invitation_limit > 0
	#     errors.add_to_base 'You have reached your limit of invitations to send.'
	#   end
	# end

	#def generate_token
	#  self.token = Digest::SHA1.hexdigest([Time.now, rand].join)
	#end
	# def decrement_sender_count
	#   sender.decrement! :invitation_limit
	# end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_filter :require_login
  def new
    @invitation = Invitation.new
    @user = current_user
    @linkwallpost= "https://www.facebook.com/dialog/feed?
  app_id=193467880799348&
  link=https://www.golazzos.com/&
  name=Visita%20Golazzos%20y%20gana%20premios&
  caption=La%20nueva%20plataforma%20de%20apuestas%20sociales%20en%20futbol&
  description=.&
  redirect_uri=http://www.golazzos.com/"

  end

  def create
    

#@linkinvitation= "http://www.facebook.com/dialog/send?app_id=116412671734664&link=http://developers.facebook.com/docs/reference/dialogs/&redirect_uri=http://www.jetsetter.com/&to=100000910418225,590528674"

        #@linkinvitation= "http://www.facebook.com/dialog/send?app_id=193467880799348&
#name=Te%20invito%20a%20que%20juegues%20conmigo%20en%20Golazzos,%20el%20juego%20divertido%20de%20futbol%20y%20gana%20fabulosos%20premios&
#link=http://www.golazzos.com/home/"+current_user.uid+"/&
#redirect_uri=http://www.golazzos.com/invitations/new"
    
    #@linkinvitation= "https://www.facebook.com/dialog/apprequests?
  #app_id=193467880799348&
  #message=Visita%20Golazzos%20y%20gana%20premios%20como%20boletas%20camisetas%20y%20balones%20cada%20mes&to="+@invitados.to_s+"&redirect_uri=http://www.golazzos.com/invitations/new"
@friends = current_user.facebook.get_connections("me", "friends?fields=id,name,picture.type(square)")
@linkinvitation= "http://www.golazzos.com/home/#{current_user.uid}"
 

    #redirect_to root_url, :notice => @mensaje
    render :msg, :notice => "Tu solicitud ha sido creada exitosamente."  

  end
  #termino create

end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_facebook_friends.html.erb
<div class="offset1 about">
	<div class="about_titulo">
		AMIGOS DE FACEBOOK
	</div>
	<div class="about_content">
    <div class="ro">
      <% @friends.each  do |friend| %>
        <%user = User.find_by_uid(friend["id"])%>
        <%if user.nil? %>
          <!-- el usuario no existe -->

          <div class= "friendship-amigo-facebook">
            <div class="friendship-foto-facebook">
              <%=image_tag friend["picture"]["data"]["url"], {:class=> "thumbsail", :width => "40px"}%>
            </div>
            <div class="friendship-nombre-facebook">
                <h5> <%=h friend["name"]%></h5>
            </div>
          </div>
          <hr/>

        <%else%>

        <%end%>
      <%end%>
    </div>
		</div>
	</div>
</div>

app/views/invitations/_send_button.html.erb
<div class="about2" span1>
	<div class="about_titulo secTitle">RETA A TUS AMIGOS</div>
	<div class="about_content">
		
         
        <p>Jugar en Golazzo$ con tus amigos es más divertido.
        <p>Podrás:
        <p>-Jugar por los marcadores de tus equipos favoritos.
        <p>-Acumular 50000 Pezzos por cada amigo que acepte. 
        <p>-Seguir la actividad de tus amigos.
         <p>-Competir con ellos para VENCER o ser HUMILLADO. 
            <hr>
        <p><strong>Invitalos aquí:</strong>
        <p>	
        <fb:send href=<%=@linkinvitation%>></fb:send>
        <p>
        	<%= link_to activities_path do%> 
            <%=image_tag "Menu/iconosMenu_Ranking.png", {:class => "", :height=>"20"}%> CONTINUAR
            <%end%>
        <p>
        
	</div>
</div>

app/views/invitations/msg.html.erb
<html xmlns:fb="http://ogp.me/ns/fb#">
  <body>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=500959623297658";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="container activities-home">
  <div class="row">
    <div class="span3">
        
      <%= render "send_button"%> 

    </div>
    <div class="span6">
      <%= render "facebook_friends"%>
    </div>
  </div>
</div>


  </body>

</html>

app/views/invitations/msg3.html.erb
<html xmlns:fb="http://www.facebook.com/2008/fbml">


  <body>
   
   <iframe src='http://localhost:3000/invitations/msg2' width=100% height=320px scrolling='no'></iframe>

  </body>
</html>

app/views/invitations/new.html.erb
<div class= "header-title">
  <div class="container">
    <div class="row">
      <p>
      <div class="span6 fuenteFuturaB titulo-blanco">
        <h3><span class="offset1">GANA MÁS PEZZOS</div></h3>
      </div>
    </div>
  </div>
</div>
<%=render "partidos/redes_sociales"%>
<div class="container">
<div class="row BTSinEspacio">
  <div class="span5 offset2 ">


<p><strong>1. AMIGOS REFERIDOS</strong>
<table class="table partidos-ranking">

    <tbody>
        <tr>
          <td>Si aceptan antes de 24 horas</td><td>recibes 50.000 PEZZOS</td>
        </tr>
        <tr>
        <td>Si aceptan entre 24 y 48 horas</td><td>recibes 20.000 PEZZOS</td>
        </tr>
        <tr>
        <td>Si aceptan después de 48 horas</td><td>recibes 0 PEZZOS</td>
        </tr>
        
        
    </tbody>
  </table>
<%= form_for (@invitation) do |f| %>
<%= f.submit "Invitar a tus amigos!" , :class => 'btn btn-primary'%>
<% end %>

<p><% link_to "Postear", @linkwallpost , :class =>"btn btn-primary"%>
<hr><p><strong>2. JUGANDO</strong>

<p>Por cada juego que realices recibes 5000 pezzos

<p><%= link_to "Juega ya", '/partidos/' , :class =>"btn btn-primary"%>


<hr><p><strong>3. LLENANDO TU PERFIL</strong>

<p>Por llenar la información de tu perfil recibes 50000 pezzos
<p><%= render "users/user_profile_boton"%>
</div>
</div>
</div>
 