config/routes.rb
Gollazos::Application.routes.draw do

  

  get "activities/index"
  get "friendship/index"
  get "redireccion/index"
  get "redireccion/new"
  get "metrics/index"
  get "metrics/emails"

  resources :invitations do
    post 'postear', :on => :collection
  end
  resources :invitacion2

  resources :partidos do
      post 'repartir', :on => :collection
      resources :bets
  end

  resources :users do
    resources :profiles
  end
  resources :redireccion
  resources :friendships
  resources :activities

  get "home/index"
  get "home/index2"
  get "home/reglamento"
  get "home/contacto"
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  match "home/:invitation_token" ,to: "home#referido"
  match "/:invitation_token" ,to: "home#index"

   root :to => 'home#index'
   

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
  	following_ids = current_user.following_ids
  	following_ids.push(1)
  	#@activities =PublicActivity::Activity.paginate(page: params[:page], per_page: 5).order("created_at desc")
  	@activities =PublicActivity::Activity.paginate(page: params[:page], per_page: 7).order("created_at desc").where(owner_id: following_ids, owner_type: "User")

  	@following= current_user.following
  	@followers= current_user.followers

  	@hora = Time.now - 1.day
  	@partidos = Partido.where("diapartido > ?", @hora).order("diapartido ASC")
  	@ranking_followers=@following.sort_by { |e| -e[:pezzos]}
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activity_agregar_amigos_facebook.html.erb
<a href="" data-toggle="modal" data-target="#myProfile">
  Agrega a tus amigos de Facebook!
</a>
<div id="myProfile" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">¡Amigos de Facebook en Golazzos!</h3>
  </div>

  <div class="modal-body">
    <p>Agrega tus amigos de Facebook a tu lista de Followings, para estar al tanto de sus jugadas y noticias! </p>

    <div>
      <div id= "users">
        <%friends = current_user.facebook.get_connections("me", "friends")%>
        <% friends.each  do |friend| %>
          <%user = User.find_by_uid(friend["id"])%>
          <%if user.nil? %>
            <!-- el usuario no existe -->

          <%else%>
            <div class= "user">
              <p>
                <strong> <%=h user.name%></strong>
                <%= link_to "Seguir", friendships_path(:friend_id => user), :method => :post  if !current_user.friendships.find_by_friend_id(user.id) %>
              </p>
            </div>
          <%end%>
        <%end%>
      </div>



    </div>
  </div>
  <div class="modal-footer">
    <button class="btn">
      Agregar Amigos 
    </button> 
       
  </div>
</div>

app/views/activities/_activity_amigos.html.erb
<div class="about">
	<div class="about_titulo secTitle">AMIGOS</div>
	<div class="about_content">
		<% @ranking_followers.each do |following|%>
		<div class="activity-ranking-follower">
			<div class="activity-ranking">
				<%= link_to following.name, following%>
			</div>
			<div class="pull-right">
				<font face="digital7" color="orange" size="3">
					<%= number_to_currency(following.pezzos,:precision => 0) %>
				</font>
			</div>
		</div>
		<%end%>
	</div>
</div>

app/views/activities/_activity_noticias.html.erb
<div class="">
	<div class="about_titulo_noticias">
		NOTICIAS
	</div>
</div>
<% @activities.each do |activity| %>
	<%=render_activity activity%>
<%end%>
<%= will_paginate%>

app/views/activities/_activity_partidos.html.erb
<div class="about">
	<div class="about_titulo secTitle">PARTIDOS</div>
	<div class="about_content"> 
		<%@partidos.each do |partido|%>
			<div class="activity-partidos">
				<div class="activity-partidos-equipos">
					<h5><%= "#{partido.local} - #{partido.visitante}" %></h5>
				    <h5><small><%= l(partido.diapartido, format: '%d de %B %l:%M %p', locale:'es-CO')%></small></h5>
				</div>
				<div class= "activity-partidos-apostar text-right">
					<%= link_to "juega!", partido, {:class => "btn btn-small"}%>
				</div>
				<hr/>
			</div>
		<%end%>
		<%= link_to "ver mas partidos", partidos_path, {:class => "text-right"}%>
	</div>
</div>

app/views/activities/_activity_perfil.html.erb
<div class="about">
	<div class="about_titulo_nombre secTitle">
		<%=image_tag current_user.facebook.get_picture(current_user.uid, {type: "square"}), {:class=> "thumbsail", :width => "40px"}%>
		<%= current_user.name.upcase%>
	</div>
	<div class="about_followers">
		<div class="about_followers_following">
		<h3><%= @following.count%></h3>
			Following
		</div>
		<div class="about_followers_following">
			<h3><%= @followers.count%></h3>
			Followers
		</div>
	</div>	
					
</div>

app/views/activities/index.html.erb
<div class="container activities-home">
	<div class="row">
		<div class="span3">
			<%= render "activity_perfil"%>
			<%= link_to "Agrega amigos!", friendships_path, {:class=> "btn btn-block"}%>
			<%= render "activity_amigos"%>	
		</div>
		<div class="span6">
			<%= render "activity_noticias"%>
		</div>
		<div class="span3">
			<%= render "activity_partidos"%>
		</div>
	</div>	 
</div>